apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ht8d93piu-java-springboot
  janus-idp.io/tekton: ht8d93piu-java-springboot
  backstage.io/kubernetes-id: ht8d93piu-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ht8d93piu-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
